export const digitalServices = [
    "*NORTON",
    "*VIBER",
    "*ZOHO CORP",
    "1NDEPENDENT NOTION",
    "21Casino",
    "24Option",
    "2Invest",
    "888Casino",
    "ACORN MEDIA GROUP",
    "Acorn TV",
    "Acquire Technology Solutions",
    "Active Campaign",
    "ACTIVECAMPAIGN",
    "ADOBE",
    "AG Technologies",
    "AIKIDO JOURNALS",
    "AIRTABLE",
    "ALFASYS",
    "ALTERIX",
    "ALTIGI",
    "AMAZNPRIME",
    "Amazon Ads",
    "AMAZON ADVERTISING LLC",
    "AMAZON DIGITAL",
    "AMAZON MUSIC",
    "AMAZON PRIME",
    "AMAZON SERVICES",
    "AMAZON VIDEO",
    "AMAZON WEB SERVICES",
    "AMAZON.COM SERVICES LLC",
    "AMAZONPRIME",
    "AMDOCS",
    "AMZ*HULU LLC",
    "ANKAMA GAMES",
    "ANYMEETING",
    "APEX TRADER FUNDING",
    "APEXTRADERFUNDING",
    "ASANA REBEL",
    "ASANA.COM",
    "ASPIEGEL",
    "Asylum Marketing",
    "Audible",
    "Automattic",
    "Avanan",
    "AVANGATE",
    "AVAST NEXWAY",
    "AVG ECOMMERCE",
    "AVG STORE",
    "AVID TECHNOLOGIES",
    "AVR*AVIRA",
    "AXESO5",
    "Axon",
    "AXON TRAINING",
    "BADOO",
    "BATTLE.NET",
    "BAYTREE LTD",
    "BDEO TECHNOLOGIES",
    "BE2 - BE2.COM.MX",
    "BE2 ? SOLTEROSCONNI",
    "BE2 S.A.R.L",
    "BE2*",
    "BEATPORT",
    "BEELINGO",
    "BEFLICK",
    "BET365",
    "Bet365 Group Ltd",
    "Betsson",
    "BETSSON.COM",
    "BETWAY",
    "BEYONDTRUST",
    "BINANCE BUY CRYPTO",
    "BINANCE.COM",
    "BITDEFENDER",
    "BITRIX, INC.",
    "Bitrix24",
    "BLIZZARD",
    "BLOOMBERG",
    "BLS*BALSOFT",
    "BLS*CONFIRMATION.COM",
    "BLS*DOMWEB.COM",
    "BLS*IMARKETSLIVE",
    "BLS*MONDAY.COM",
    "BLS*MYHERITAGE LTD Z",
    "BLS*MYHERITAGE_LTD",
    "BLS*SWIFTIC F K A COMO",
    "BLS*SWIFTIC F.K.A COMO",
    "BLUEHOST",
    "BMJPUBLISHI",
    "BMJPUBLISHING",
    "BOLD",
    "BQ Support",
    "BRIGHT MARKET LLC",
    "Brock Solutions",
    "BrowserStack",
    "BROWSERSTACK INC",
    "BUDDHIFY",
    "BULB QUALITY SUPPORT B.V.",
    "BULLGUARD",
    "BUMBLE",
    "BUMBLEBEE",
    "BUZZFEED",
    "Bwin",
    "Bytro Labs",
    "CALENDLY",
    "CALLBELL",
    "Candy Crush",
    "CANVA",
    "CASPIO INC",
    "CASPIO, INC",
    "CBA*WEBNODE",
    "CBI*AVIRA",
    "CERBERUS ANDROID",
    "CEX.IO",
    "CGCH CONCEPTS GRO",
    "Checklist Facil",
    "Chronicle Books",
    "CHRONICLE LLC",
    "CipSoft",
    "CITRIX",
    "CKO*HOSTINGER",
    "Cleverbridge",
    "CLICKDESK-855",
    "CLICKUP",
    "Clientify",
    "CLOUD GAMES",
    "CLOUDBEES",
    "Coaching Kale Anders",
    "CODASHOP",
    "CODE42.COM",
    "CODEABLEAPS",
    "CODEALIKE",
    "CODEANDGROW",
    "CODEANDSUPPLY",
    "CODEANDWEB",
    "CODEANYWHERE",
    "CODEASILY",
    "CODEAVENGERS",
    "Codigo Petaccia",
    "CODIGOAPEX",
    "CODIGOPETACCIA",
    "CODINGAME",
    "Cognex",
    "COGNEX CORPORATION",
    "COGNOSONLIN",
    "COIN MASTER",
    "COINBASE",
    "COINMASTER",
    "COLUMBIA JOURNAL",
    "COLUMBIA JOURNALISM",
    "CONFIRMATION.COM",
    "CONTABO",
    "ContentStuff",
    "CoolBet",
    "Copywriting de otra Galaxia",
    "COSMIC GO PAYMENT",
    "Coursera",
    "cPanel",
    "CRUNCHYROLL",
    "CRYPTO.COM",
    "CSIDATE.NET",
    "CSOCDATE.NET",
    "CURB SVC",
    "DAZN",
    "DDITSERVICES.COM",
    "DEEZER",
    "DELLMONT",
    "DELLMONT.COM",
    "DGNET LTD.",
    "DIANDIAN",
    "Dicom Smart",
    "DICOMSMART MEDICAL SYSTEMS, INC.",
    "DIDACTOONS",
    "DiDi",
    "DigiCert",
    "DIGIMEDIA LIMITED",
    "DIGITAL RIVER",
    "DigitalOcean",
    "DIGITALRIVER",
    "Discord",
    "DIVASPLAY",
    "DOCTORALIA",
    "DOCTORSIM.COM",
    "DOG PRODUCTIONS LTD.",
    "Domestika",
    "DOMINION FUND MANAGEMENT",
    "Dominion Funds",
    "DOMWEBCOM AR",
    "Dorado Games",
    "DOT Hotels",
    "DOTSTER",
    "DOWNDOGAPP.COM",
    "DREAM GAMES ",
    "DREAMGAMES ",
    "DRI*AVAST",
    "DRI*MYFAMILYCINEMA 9 ",
    "DRI*NETMAKE SOLUCOES ",
    "DRIAVAST",
    "DROPBOX",
    "Duodecad IT Services",
    "DUOLINGO",
    "DYNATRACE",
    "Dysopsis",
    "EA PLAY",
    "EA SWISS SARL",
    "EAE Business School",
    "EAE ONLINE",
    "ECHST",
    "EDITIONS ENI",
    "EDITORIAL TIRANT LO BLANCH SL",
    "Edvolution",
    "EIG*CONSTANTCONTACT ",
    "EIG*VERIO ",
    "EL ULTIMO GEEK SA DE CV",
    "ELASTIC SEARCH",
    "ELASTICSEARCH",
    "ELECTRAWORKS",
    "Electronic Arts",
    "Elsevier",
    "ELSEVIER",
    "ENEBA.COM",
    "EnfraGen",
    "ENFRAGEN LLC",
    "Entain Partners",
    "ENVATO",
    "EPIC GAMES",
    "EPICGAMES",
    "eRepublik Labs",
    "ESET LLC",
    "ESHOP WORLD",
    "eShopWorld",
    "ETEACHER",
    "ETEACHER GROUP LTD",
    "ETORO",
    "Etsy",
    "EuroPalace Casino",
    "EVIMEDNET",
    "EX_BROKERIQ",
    "Expensify",
    "ExpressVPN",
    "EXPSTUDIO",
    "EZVIZ",
    "FACEBK",
    "FACEBOOK",
    "FACEIT",
    "FACETUNE",
    "FASTMAIL+PTY+LTD&HL",
    "FastSpring",
    "Fenix International",
    "FIGMA",
    "FILMORAGO",
    "FINANCIAL TIME LT",
    "FINANCIAL TIME LTD",
    "FITBIT COACH FITBIT CO",
    "FITBIT COACH PREMIUM",
    "FITBIT, INC.",
    "FITOCRACY",
    "FL STUDIO",
    "FLIGHTRADAR24 AB",
    "FLOKZU",
    "FORTNITE ",
    "FOZ-ICE/BUMBLEBEE",
    "FREEHOSTING",
    "FREEHOSTING.COM",
    "Freelancer",
    "FREEPIK",
    "FreshWorks",
    "Frontiers Media",
    "FSPRG.NL",
    "Funimation",
    "Futbol Club Barcelona",
    "FXCLUB.ORG",
    "G2A",
    "G2A.COM",
    "GAMEFORGE GAMES",
    "GAMESROCKS.NET",
    "GARENA",
    "Geocaching",
    "Geocelu.com",
    "GEOCELU.COM",
    "GET ON BOARD HOLDING CORP",
    "GETNAVE",
    "Getonboard",
    "GETTY IMAGES",
    "GIGHUB",
    "GITHUB",
    "GITLAB",
    "Global Rate Set Systems",
    "Global Strategic Marketing",
    "Global.ITRADER",
    "GLOUD GAMES",
    "GODADDY",
    "GOG SPOLKA Z OGRANICZONA ODPOWIEDZIALNOSCIA",
    "GOGcom",
    "GOOGLE *",
    "GOOGLE ANDROID",
    "GOOGLE LLC",
    "GOOGLE PLAY",
    "GOOGLE PZIZZ",
    "GOOGLE STORAGE",
    "GOOGLE*",
    "GRABR.IO* G ",
    "GRAMMARLY",
    "GRAVITY INT",
    "GRINDR",
    "GROUNDSPEAK, INC.",
    "Guts Casino",
    "GVC SERVICES LIMITED",
    "Gympass",
    "HABITISSIMO",
    "HANSARD",
    "Hansard Global",
    "HAPPN",
    "HASHFLARE",
    "HBO DIG",
    "HBO MAX",
    "HBOMax",
    "HBOSTORE",
    "HDS*HEADSPACE ",
    "HEADSPACE MEDITATION LTD",
    "Heed 360",
    "Heroku",
    "High Morale Developments",
    "HIKARI",
    "HIKARI LTD",
    "HLU* ",
    "HOLCOMB FINANCE LIMITED",
    "HOO",
    "HOO.COM",
    "HOSTGATOR",
    "HOSTINGER",
    "HOSTINGER INTERNATIONAL",
    "HOTJAR",
    "HOTMART",
    "HTTPS//LEVELUP.DIGITAL",
    "HTTPS://APPS.APPLE.COM/TUTANOTA",
    "HUAWEI CLOUD",
    "HUAWEI SERVICES",
    "Huawei Services",
    "HUAWEICLOUD",
    "HUAWEISERVICES",
    "HubSpot",
    "HULU LLC",
    "Humble Bundle",
    "HUMOR RAINBOW INC",
    "IC MARKETS",
    "ICLOUD",
    "IDT CORPORATION DE 000000000338420",
    "IGG MOBILEGAME",
    "IM Academy",
    "IMARKETSLIVE",
    "IMDB",
    "INGRAM MICRO",
    "INGRAMMICRO",
    "INMOTIIONHOSTING.COM",
    "InnoGames",
    "INNOVA CO SARL",
    "INSTAGRAM",
    "INSTANT GAMING",
    "INTELISOFT WS LLC",
    "Intercom (Business Messenger)",
    "INTERCOM.IO",
    "Interdate",
    "INTERDATE SA",
    "INTERMEDIA ANYMEETING",
    "Intime Desarrollos Informaticos",
    "INTIME DESARROLLOS INFORMATICOS SL",
    "Inversor Global",
    "INVERSOR GLOBAL",
    "IPAGE",
    "IQ Option",
    "IQOPTION",
    "IQOPTION.COM",
    "IRON GYM",
    "IStock",
    "ISTOCK.COM",
    "ITE Soluciones",
    "ITE SOLUCIONES SA DE CV",
    "ITUNES.COM",
    "IWS",
    "IWS INTERNATIONAL WEB SERVICES AG",
    "Jackpot City",
    "JEFIT, INC",
    "JHUP JOURNALS",
    "JIMDO",
    "JOHN WILEY & SONS, INC.",
    "JOHNS HOPKINS UNIVERSITY PRESS",
    "JUNIPERTECH",
    "JustAnswer",
    "JUSTANSWER",
    "KABAM GAMES",
    "KALE ANDERS",
    "KASPERSKY",
    "KING.COM",
    "KINGSGROUP",
    "Kizeo",
    "KIZEO SAS",
    "KLAB",
    "KLETT SPRACHEN",
    "KONAMI",
    "KYLA ITSINES",
    "LA EMPRESA MAIL TRACK S.L",
    "LABWARE",
    "LATAM STREAMCO INC.",
    "Latam Streaming",
    "LEADUCATE",
    "LEARNING SANOMA",
    "LEIDEN TECHNOLOGY DO B",
    "LEIDEN TECHNOLOGY DO B*",
    "LEVEL UP INTERACTIVE",
    "LEVELUP*SMOOTHIEKING63 ",
    "LEVELUPCOINS",
    "LEVELUPHONEYGROW",
    "LEVELUPLIFE",
    "LEVELUPMODERNMARKETEA",
    "Lexum",
    "LEXUM INFORMATIQUE JURIDIQUE INC.",
    "LIBERTEX",
    "LIBERTEX.ORG",
    "LILITH MOBI",
    "LIME",
    "LINKEDIN",
    "Linode",
    "LIVEJOURNAL",
    "LIVEU",
    "LOGICSHARE LLC",
    "LOGMEIN IRELAND LIMITED",
    "LogMeIn Ireland Ltd.",
    "LOGMEIN*GOTOMEETING",
    "LONG TECH",
    "LOVOO.COM",
    "MAGENTO INC",
    "MAGIC NOTION",
    "Mailblast",
    "MAILBLAST S.A. DE C.V.",
    "MAILCHIMP",
    "MAILGUN",
    "Mailtrack",
    "MASSIVE MEDIA",
    "MATCH GROUP INC",
    "Match.com",
    "MATCH.COM LATAM LIMITED",
    "MCAFEE",
    "MDPI AG",
    "MEDIAFIRECHARGECOM",
    "MEETIC.COM",
    "MEGA CLOUD SERVICES",
    "MEGA LTD",
    "Meister",
    "MEISTERLABS GMBH",
    "MELESTA GAMES",
    "MERCADOPAGO*PINKERTON SA ",
    "META",
    "METASTOCK",
    "MICROSOFT",
    "Milvus",
    "MIRO.COM",
    "MITBLADDK",
    "MOCO STUDIOS",
    "Modyo",
    "MODYO SPA",
    "MOJANG",
    "Mojang Studios",
    "MONDAY MOVERS",
    "MongoDB Cloud",
    "MONGODB.COM",
    "MONGODBCLOUD",
    "MONOCLE",
    "MONOCLE MONOCLE",
    "MONOPOLY",
    "MOON ACTIVE",
    "MOONACTIVE",
    "MOONFROG LABS",
    "MOVAVI",
    "MSFT * ",
    "MSLI LATAM, INC.",
    "MTV NETWORKS LATIN AMERICA INC.",
    "MTVLA",
    "MUBI",
    "Multidisciplinary Digital Publishing Institute",
    "MYFITNESSPAL",
    "MYHERITAGE",
    "MYHERITAGE LTD",
    "MYHERITAGECOM",
    "MYSS.COM",
    "MZ CONSULT NY LLC",
    "MZ Group",
    "NAPSTER FRANCE",
    "NAPSTER INFORMATICA",
    "NASDAQ",
    "NBA League pass",
    "NBA Media Ventures, LLC.",
    "NETDRAGON WEBSOFT LTD",
    "NETFLIX",
    "NETMARBLE",
    "NEW YORK TIMES",
    "NEXWAY",
    "NIANTIC INC",
    "NILTASOFT LIMITED",
    "NINTENDO",
    "NORDVPN",
    "NORTON *",
    "Norton Antivirus",
    "NORTONLIFELOCK INC.",
    "NOTION DESIGN",
    "NOTION ENTERPRISES",
    "NOTION LABS",
    "NOTION STUDIOS",
    "NOTION.SO",
    "NOTIONHOST",
    "NYT*NYT TIME SYNDICATE",
    "OAKTREE SOFTWARE",
    "OASIS GAMES",
    "ODOO",
    "OFFGAMERS",
    "ONE DRIVE",
    "ONLYFANS",
    "OPENENGLISH.COM",
    "OVERTIER OPERATIONS",
    "Overtier Operations",
    "OVH.COM",
    "PADDLE PAYMENTS LIMITED",
    "Paddle.com",
    "PADDLE.NET",
    "PANDA SECURITY",
    "PARADISE PUBLISHER",
    "PARAMOUNT",
    "Party Casino",
    "PASSLINE",
    "PASSLINE B",
    "PATREON",
    "PAYPAL *DONWEBCOM",
    "PAYPAL *ETEACHERGRO",
    "PAYPAL *HOSTINGER",
    "PAYPAL *PREZIBASE",
    "PAYPAL *TAKE 2 INC",
    "PAYPAL *TAKE2AUCTIO",
    "PAYPAL *WORKANA LLC",
    "PayPro Global",
    "PAYPRO GLOBAL, INC.",
    "PCLOUD",
    "Pearson Virtual University Enterprises",
    "PEARSON VUE",
    "PHANTOM EFX",
    "PHANTOMBUSTER",
    "PHOTOBUMBLE.COM",
    "PINKERTON",
    "PIPEDRIVE",
    "PIPEFY",
    "Pitney Bowes",
    "PITNEYBOWES",
    "PIXABAY",
    "PLAYRIX GAMES",
    "PLAYSTATION NETWORK",
    "PLAYSTATIONNETWORK",
    "PLUS500",
    "Pokemon Go",
    "PREZI INC",
    "PRICEWATERHOUSECOOPERS SERVICES B.V.",
    "PRIME VIDEO",
    "Project Management Institute",
    "PROJECT MANAGEMENT INSTITUTE INC. (PMI)",
    "ProQuest Dialog",
    "PROQUEST LLC",
    "PROTEGE.LA/TUTANOTA",
    "PROXIMA BETA PTE. LIMITED",
    "PRZ*CHARGE.PREZI.COM",
    "PT ENTERTAINMENT SERVICES",
    "PTM",
    "PTM EDV SYSTEME GMBH",
    "Publicaciones digitales",
    "PwC",
    "PZIZZ",
    "QINT",
    "QUELLO CONCERTS",
    "QUERYLOOP",
    "QUICK HEAL",
    "RackSpace",
    "READSPEAKER WEBSERVICES",
    "REBTEL",
    "REVOLUT",
    "RI *",
    "RIOT GAMES",
    "RIOTGAM*",
    "RIOTGAMES",
    "ROBLOX",
    "ROCKSTAR GAMES",
    "ROKU",
    "ROYAL MATCH",
    "ROYALMATCH",
    "RUNTASTIC",
    "SAGAL",
    "SAGE PUBLICATIONS",
    "SALESFORCE",
    "Sandbox Interactive",
    "SASCHA FITNESS",
    "SC-ETEACHER AMSTERDAM",
    "SCHOLASTIC EDUCATION",
    "SCREENCAST",
    "SCRIBD",
    "SECURITY SHIELD",
    "SEGA",
    "SEGA III",
    "SENDINBLUE",
    "Sherpals",
    "Shutterstock",
    "SHUTTERSTOCK INC.",
    "SITEGROUND",
    "SKED24",
    "SKR*UNITED GAMES GMBH",
    "SKYPE",
    "SKYPE SUBSCRIPTION SKYPE",
    "SKYPE.COM",
    "SLACK",
    "SMALL GIANT",
    "SMILES FIDELIDADE SA*B",
    "SNAPCHAT",
    "SOCIAL ONLINE PAYMENTS",
    "SOFTLAYER TECHNOLOGIES",
    "Softline",
    "SOFTWARENOTION",
    "SOLARWINDS",
    "SPORTINGBET",
    "SPOTIFY",
    "SQUARE ENIX",
    "SQUARESPACE",
    "STALEX DIGITAL SERVICES",
    "Stalex Media",
    "Starkey Hearing Technologies",
    "STARKEY LABS INC",
    "STARS",
    "Stars Group Inc",
    "STAYCOOL",
    "STEAMGAMES.COM",
    "STEAMPOWERED.COM",
    "STREAMRAY",
    "STRONGTRAINING AF",
    "SUGARSYNC",
    "SUPERCELL",
    "SURFSHARK",
    "SurveyMonkey",
    "SWAG MASHA",
    "TEA EDICIONES",
    "Teachable",
    "Teamviewer",
    "TEAMVIEWER.COM",
    "TECNOLINK S.A.",
    "TELEFONICA GLOBAL SERV",
    "Tencent Games",
    "Tenedora de Cines",
    "TERAVISTA TECHNOLOGIES",
    "The Bikini Body Training Company",
    "THE ECONOMIST",
    "THE FINANCIAL TIMES",
    "THE ROCKET SCIENCE GROUP, LLC",
    "THE SURFER'S JOURNAL",
    "THEGCODEALGO.COM",
    "THELOTTER",
    "THEMA",
    "THEMEFOREST",
    "TIDAL MUSIC",
    "TIKTOK",
    "TIMES NEWSPAPERS LTD",
    "TIMETASTIC",
    "TINDER",
    "Tirant Lo Blanch",
    "TITAN 3PL",
    "TitanBet.co.uk",
    "TOEFL SERVICES",
    "TOP GAMES",
    "TOTALAV",
    "TradeCore",
    "TRADINGVIEW",
    "TRAINA",
    "TRAINING SOLUTIONS",
    "TRAINING SOLUTIONS LTD",
    "TRAVELCLICK",
    "TRAVIAN GAMES",
    "TRIPADVISOR",
    "TRUVALIA",
    "TSG GWS GERMANY GMBH",
    "TUMBLR INC",
    "TUNEINTUNES.COM",
    "TWITCH",
    "TWITTER",
    "TYPEFORM",
    "U.S. Pharmacopeial",
    "UBISOFT",
    "UDEMY",
    "UNBOUNCE",
    "UNIVERSITY OF CHICAGO PRESS JOURNALS",
    "UNPLASH",
    "UPHOLD.COM",
    "UPTODATE",
    "UPWORK",
    "US PHARMACOPEIAL CONV",
    "UYCARMELA PUBLICIDA",
    "VALVE",
    "VALVE CORPORATION",
    "Various",
    "VARIOUS, INC.",
    "VENDOSTORE*",
    "VERBOLIA",
    "VGLOBAL DSL",
    "VIAGOGO",
    "VIBER",
    "VIBER EU",
    "VIBER EUR",
    "VIKI",
    "VIMEO",
    "VIRTUNET",
    "VOXY ENGLISH COURSE",
    "VTIGER SYSTEMS",
    "WAHOO",
    "WARNER BROS",
    "WARNERBROS",
    "WEB*NETWORKSOLUTIONS",
    "WEBEX.COM",
    "WEBFLOW",
    "WEBNODE AG",
    "WEBSYDIAN",
    "WEEBLY",
    "WEIGHTWATCHERS",
    "WHITE HAT GAMING",
    "WILD WEST DOMAINS",
    "Wiley",
    "WISDOM WAY",
    "WISH.COM",
    "WIX",
    "WIX.COM",
    "Wizard of Web",
    "WIZARD OF WEB LTD",
    "Wolfram Alpha",
    "WOLFRAM ALPHA LLC",
    "WONDERBLY",
    "WONDERSHARE",
    "Woocommerce",
    "WOOD WORKERS JOURNAL",
    "WORDPRESS",
    "WORKANA",
    "WORKANA LLC",
    "WORKANA. WORKANA",
    "WWE NETWORK",
    "WWW SKY COM",
    "WWW.AVIRA.COM",
    "WWW.CRASHPLAN.COM",
    "WWW.DAILYYOGA.COM",
    "WWW.DOMWEB.COM",
    "WWW.GETTYIMAGES.COM",
    "WWW.SKYPE.COM",
    "WWW.STEAMPOWERED.COM",
    "XBGlobal.com",
    "XSOLLA *",
    "XSOLLA.COM",
    "XSOLLAS",
    "XTB",
    "YAHOO SMALL BUSINESS",
    "YOLA",
    "YOLA INC",
    "YOLA.COM",
    "YOOZOO",
    "YOUNGJOY",
    "Your Aussie Life",
    "YOUR AUSSIE LIFE PTY L",
    "YOUTUBE",
    "ZAPIER",
    "ZAPPING TV",
    "ZECURE GAMING LIMIT",
    "ZENKIT",
    "ZOHO CORPORATION",
    "ZOHO-13408479-COMMERCE",
    "ZOHO-CRM",
    "ZOHO-ONE",
    "ZOOM ZOOM",
    "ZOOM.US",
    "ZOOM.US 888-799-9666",
    "ZUMBA FITNESS",
    "ZUMBA.COM",
];